name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  stub-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          # Stable as of June/July 2025; pin to avoid surprises
          version: '25.04.6'

      - name: Print versions
        run: |
          java -version
          nextflow -version

      - name: Smoke test (stub-run)
        run: |
          mkdir -p report
          nextflow run workflows/main.nf \
            -stub-run -profile standard \
            -with-report report/report.html \
            -with-trace -with-timeline
          test -s report/report.html

      - name: Upload stub report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stub-report
          path: report/report.html
